apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "bwcemon.fullname" . }}
  labels:
{{ include "bwcemon.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bwcemon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bwcemon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: PERSISTENCE_TYPE
            value: "postgres"
          - name: DB_URL
            value: "postgresql://tibco:Tibco123!@127.0.0.1/bwcemon"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.internalPort }} 
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: "{{ .Chart.Name }}-bwcemondb"
          image: "{{ .Values.imagedb.repository }}:{{ .Values.imagedb.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: POSTGRESQL_USERNAME
            value: "tibco"
          - name: POSTGRESQL_PASSWORD
            value: "Tibco123!"
          - name: POSTGRESQL_DATABASE
            value: "bwcemon"
          ports:
          - containerPort: {{ .Values.service.dbinternalPort }}          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
