apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ include "bwcemon.fullname" . }}
{{- end }}
  labels:
{{ include "bwcemon.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.ingress.enabled -}}
    fabric8.io/exposeUrl: {{ .Values.ingress.host }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "bwcemon.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
